### ISSUE TITLE
Interesting work!

### ISSUE THREAD

**Issue by joshuaquek** [emkay/theodore#1]
Interesting work! How does this differ from other http server libraries?

**Comment by emkay** [comment]
Thanks! It uses [`turbo-http`](https://github.com/mafintosh/turbo-http) under the hood which is super fast. On my laptop I'm getting ~30k req/s on simple routes. I wanted an easy API to build json servers, but wanted the speed of `turbo-http`.

**Comment by joshuaquek** [comment]
cool! I think it would be cool to mention under the readme that it uses Turbo HTTP (cos thats the main selling point I feel) and that it can handle a higher number of requests as compared to regular express.

Anyway it looks great man! :D
